# Generated by Django 3.1.7 on 2022-03-26 21:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('birthdate', models.DateField(default=None)),
                ('role', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'goldCustomer'), (2, 'platinumClub'), (3, 'primeService')], default=1, max_length=5)),
            ],
        ),
    ]
